#!/usr/bin/env python3

from __future__ import annotations

import importlib
import importlib.util
import pathlib
import sys


DEFAULT_ZONEINFO_DIR = pathlib.Path("/usr/share/zoneinfo")

SKIP_NAMES = {
    "iso3166.tab",
    "leap-seconds.list",
    "leapseconds",
    "localtime",
    "posixrules",
    "tzdata.zi",
    "zone.tab",
    "zone1970.tab",
}

SKIP_PREFIXES = (
    "posix/",
    "right/",
)


def escape_c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def build_header(source: str) -> str:
    return f"/* Auto-generated by misc/generate_tzones.py from {source}. */"


def find_tzdata_zoneinfo_dir() -> pathlib.Path | None:
    try:
        spec = importlib.util.find_spec("tzdata")
        if spec is None:
            return None

        module = importlib.import_module("tzdata")
        module_file = getattr(module, "__file__", None)
        if module_file is None:
            return None

        zoneinfo_dir = pathlib.Path(module_file).resolve().parent / "zoneinfo"
        if zoneinfo_dir.is_dir():
            return zoneinfo_dir
    except (ImportError, AttributeError):
        pass

    return None


def resolve_zoneinfo_dir(zoneinfo_arg: str | None) -> tuple[pathlib.Path, str]:
    if zoneinfo_arg is not None:
        zoneinfo_dir = pathlib.Path(zoneinfo_arg)
        if not zoneinfo_dir.is_dir():
            raise SystemExit(f"zoneinfo directory not found: {zoneinfo_dir}")
        return zoneinfo_dir, str(zoneinfo_dir)

    if DEFAULT_ZONEINFO_DIR.is_dir():
        return DEFAULT_ZONEINFO_DIR, str(DEFAULT_ZONEINFO_DIR)

    tzdata_zoneinfo_dir = find_tzdata_zoneinfo_dir()
    if tzdata_zoneinfo_dir is not None:
        return tzdata_zoneinfo_dir, "the Python tzdata package"

    raise SystemExit(
        f"zoneinfo directory not found: {DEFAULT_ZONEINFO_DIR}. "
        "Install the Python package 'tzdata' or pass ZONEINFO_DIR explicitly."
    )


def extract_tzif_footer(zone_file: pathlib.Path) -> str | None:
    data = zone_file.read_bytes()

    if len(data) < 5 or data[:4] != b"TZif":
        return None

    last_newline = data.rfind(b"\n")
    if last_newline <= 0:
        return None

    prev_newline = data.rfind(b"\n", 0, last_newline)
    if prev_newline < 0:
        return None

    footer = data[prev_newline + 1:last_newline].decode("ascii", errors="strict").strip()
    return footer or None


def iter_zoneinfo_entries(zoneinfo_dir: pathlib.Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []

    for path in sorted(zoneinfo_dir.rglob("*")):
        if not path.is_file():
            continue

        rel_path = path.relative_to(zoneinfo_dir).as_posix()
        if rel_path in SKIP_NAMES or rel_path.startswith(SKIP_PREFIXES):
            continue

        footer = extract_tzif_footer(path)
        if footer is None:
            continue

        entries.append((rel_path, footer))

    if not entries:
        raise SystemExit(f"no timezone entries found under {zoneinfo_dir}")

    return entries


def build_include(entries: list[tuple[str, str]], source: str) -> str:
    lines = [build_header(source)]
    lines.append("const TZName_t TimeZones[] = {")
    for name, tzname in entries:
        lines.append(f'    {{ "{escape_c_string(name)}", "{escape_c_string(tzname)}" }},')
    lines.append("};")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) not in {3, 4} or argv[1] != "build":
        print(f"usage: {argv[0]} build OUTPUT_INC [ZONEINFO_DIR]", file=sys.stderr)
        return 1

    output_path = pathlib.Path(argv[2])

    zoneinfo_arg = argv[3] if len(argv) == 4 else None
    zoneinfo_dir, source = resolve_zoneinfo_dir(zoneinfo_arg)
    entries = iter_zoneinfo_entries(zoneinfo_dir)
    output_path.write_text(build_include(entries, source), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))