#!/usr/bin/env python3

import pathlib
import re
import sys


PLACEHOLDER_RE = re.compile(r"%([A-Z0-9_]+)%")


def minify_html(content: str) -> str:
    content = re.sub(r"<!--.*?-->", "", content, flags=re.S)
    content = re.sub(r">\s+<", "><", content)
    content = re.sub(r"\s+", " ", content)
    return content.strip()


def escape_c_string(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
        .replace("\t", " ")
    )


def split_c_string(text: str, chunk_len: int = 120) -> list[str]:
    if not text:
        return ['""']

    escaped = escape_c_string(text)
    chunks: list[str] = []
    idx = 0

    while idx < len(escaped):
        end = min(idx + chunk_len, len(escaped))

        while end < len(escaped):
            backslash_count = 0
            probe = end - 1

            while probe >= idx and escaped[probe] == "\\":
                backslash_count += 1
                probe -= 1

            if backslash_count % 2 == 0:
                break

            end -= 1

        if end == idx:
            end = min(idx + chunk_len, len(escaped))

        chunks.append(f'"{escaped[idx:end]}"')
        idx = end

    return chunks


def placeholder_to_handler(placeholder: str) -> str:
    return f"http_data_{placeholder.lower()}"


def build_template_entries(content: str) -> list[tuple[str, str | None]]:
    entries: list[tuple[str, str | None]] = []
    cursor = 0

    for match in PLACEHOLDER_RE.finditer(content):
        entries.append((content[cursor:match.start()], placeholder_to_handler(match.group(1))))
        cursor = match.end()

    entries.append((content[cursor:], None))
    return entries


def emit_header(entries: list[tuple[str, str | None]]) -> str:
    lines: list[str] = [
        "/* Auto-generated by misc/split_to_template.py. Do not edit manually. */",
        "static const web_template_chunk_t s_index_template[] = {",
    ]

    for const_html, handler in entries:
        lines.append("    {")
        for part in split_c_string(const_html):
            lines.append(f"        {part}")
        if handler is None:
            lines.append("        ,")
            lines.append("        NULL,")
        else:
            lines.append("        ,")
            lines.append(f"        {handler},")
        lines.append("    },")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} INPUT_HTML OUTPUT_HEADER", file=sys.stderr)
        return 1

    input_path = pathlib.Path(sys.argv[1])
    output_path = pathlib.Path(sys.argv[2])
    content = input_path.read_text(encoding="utf-8")
    output_path.write_text(emit_header(build_template_entries(minify_html(content))), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())